import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {parseApp,parseResponse,requestBody,fetchPage} from './google-play.mjs';
import {collect,api} from './worker.mjs';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));const wrap=(query,args=[])=>({bind(...values){return wrap(query,values)},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}});return {sql,prepare:wrap,async batch(statements){sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
function wire(id='id-1',content='Good app',cursor='next'){const raw=[id,null,5,null,content,[Math.floor(Date.now()/1000)],3,null,null,null,'1.0'];return ")]}'\n\n"+JSON.stringify([['wrb.fr','oCPfdb',JSON.stringify([[raw],[null,cursor],[]])]]);}
const req=body=>new Request('https://example.com/api/collect',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:JSON.stringify(body)});
const fetcher=async()=>new Response(wire());
test('edge-compatible redirect policy rejects sign-in redirects',async()=>{await assert.rejects(fetchPage('com.test',null,async(url,options)=>{assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://example.com/signin'}});}),/HTTP 302/);});
test('app input accepts a Play link and rejects arbitrary URLs and names',()=>{assert.equal(parseApp('https://play.google.com/store/apps/details?id=com.ubercab'),'com.ubercab');for(const v of ['Google Maps','https://evil.example/?id=com.ubercab','https://play.google.com/store/apps/details?id=com.a&id=com.b'])assert.throws(()=>parseApp(v));});
test('wire request includes sort newest and continuation token',()=>{const body=JSON.parse(new URLSearchParams(requestBody('com.test','abc')).get('f.req'));const args=JSON.parse(body[0][0][1]);assert.equal(args[1][1],2);assert.deepEqual(args[1][2],[25,null,'abc']);});
test('malformed responses cannot be mistaken for zero reviews',()=>{assert.throws(()=>parseResponse('<html>Verify</html>','com.test','today'));assert.throws(()=>parseResponse(wire('id',''),'com.test','today'));assert.equal(parseResponse(wire(),'com.test','today').records[0].score,5);});
test('repeated collection updates one record and stores separate page evidence',async()=>{const DB=database();const env={DB};for(let i=0;i<2;i++){const r=await collect(req({app:'com.test',label:'Test'}),env,fetcher);assert.equal(r.status,200);DB.sql.exec('DELETE FROM app_locks');}assert.equal(DB.sql.prepare('SELECT count(*) AS n FROM reviews').get().n,1);assert.equal(DB.sql.prepare('SELECT count(*) AS n FROM pages').get().n,2);});
test('failed next page preserves cursor and committed records; retry resumes',async()=>{const DB=database();const first=await (await collect(req({app:'com.test'}),{DB},fetcher)).json();DB.sql.exec('DELETE FROM app_locks');const failed=await collect(req({resume:first.run_id}),{DB},async()=>new Response('bad'));assert.equal(failed.status,502);assert.equal(DB.sql.prepare('SELECT pages,cursor FROM runs').get().pages,1);assert.equal(DB.sql.prepare('SELECT cursor FROM runs').get().cursor,'next');DB.sql.exec('DELETE FROM app_locks');const resumed=await collect(req({resume:first.run_id}),{DB},async()=>new Response(wire('id-2','Later',null)));assert.equal(resumed.status,200);assert.equal(DB.sql.prepare('SELECT count(*) AS n FROM reviews').get().n,2);});
test('database error rolls back reviews, evidence and progress together',async()=>{const DB=database();DB.sql.exec("CREATE TRIGGER fail_page BEFORE INSERT ON pages BEGIN SELECT RAISE(ABORT,'forced storage failure'); END;");const response=await collect(req({app:'com.test'}),{DB},fetcher);assert.equal(response.status,502);assert.equal(DB.sql.prepare('SELECT count(*) AS n FROM reviews').get().n,0);assert.equal(DB.sql.prepare('SELECT pages FROM runs').get().pages,0);});
test('exact app name isolates app instead of matching mentions; filters work',async()=>{const DB=database();await collect(req({app:'com.spotify.music',label:'Spotify'}),{DB},fetcher);await collect(req({app:'com.test',label:'Other'}),{DB},async()=>new Response(wire('id-2','Spotify is mentioned')));const response=await api(new Request('https://example.com/api/reviews?q=Spotify&helpful=1'),{DB});const d=await response.json();assert.equal(d.total,1);assert.equal(d.reviews[0].app_id,'com.spotify.music');const no=await (await api(new Request('https://example.com/api/reviews?rating=low'),{DB})).json();assert.equal(no.total,0);});
test('cross-origin collection is rejected before writing',async()=>{const DB=database();const r=req({app:'com.test'});r.headers.set('Origin','https://other.example');assert.equal((await collect(r,{DB},fetcher)).status,403);assert.equal(DB.sql.prepare('SELECT count(*) AS n FROM runs').get().n,0);});
test('shared rate limit prevents an upstream request',async()=>{const DB=database();DB.sql.prepare('INSERT INTO request_limits VALUES (?,60,?)').run('hour:'+Math.floor(Date.now()/3600000),Date.now()+3600000);assert.equal((await collect(req({app:'com.test'}),{DB},()=>{throw Error('must not fetch');})).status,429);});
